version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql4scanglish
    restart: always
    ports:
      - "3310:3306"
    env_file:
      - .env
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - scanglish_net
volumes:
  mysql_vol:
networks:
  scanglish_net:
